# Generated by Django 2.2.5 on 2019-12-19 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webSite', '0002_auto_20191219_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='PresentationStudent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='webSite.PresentationStudent'),
        ),
        migrations.AlterField(
            model_name='presentationstudent',
            name='guid_instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='webSite.Professor'),
        ),
    ]
