# Generated by Django 2.2.5 on 2019-12-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webSite', '0004_auto_20191219_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='doc1',
        ),
        migrations.AddField(
            model_name='presentationstudent',
            name='doc1',
            field=models.FileField(blank=True, upload_to='doc1'),
        ),
        migrations.AddField(
            model_name='presentationstudent',
            name='doc2',
            field=models.FileField(blank=True, upload_to='doc2'),
        ),
    ]
