# Generated by Django 2.2.5 on 2019-12-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webSite', '0005_auto_20191219_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentationstudent',
            name='doc1',
        ),
        migrations.RemoveField(
            model_name='presentationstudent',
            name='doc2',
        ),
        migrations.AddField(
            model_name='presentationstudent',
            name='doc',
            field=models.FileField(blank=True, upload_to='doc2'),
        ),
        migrations.AddField(
            model_name='presentationstudent',
            name='pdf',
            field=models.FileField(blank=True, upload_to='doc1'),
        ),
    ]
