# Generated by Django 2.2.5 on 2019-12-26 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webSite', '0006_auto_20191219_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='doc',
            field=models.FileField(blank=True, upload_to='doc2'),
        ),
        migrations.AddField(
            model_name='student',
            name='guid_instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='webSite.Professor'),
        ),
        migrations.AddField(
            model_name='student',
            name='pdf',
            field=models.FileField(blank=True, upload_to='doc1'),
        ),
        migrations.DeleteModel(
            name='PresentationStudent',
        ),
        migrations.AddField(
            model_name='student',
            name='Semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webSite.Semester'),
        ),
    ]
