# Generated by Django 2.2.5 on 2019-12-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webSite', '0008_auto_20191227_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='company_name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
