# Generated by Django 2.2.5 on 2019-12-27 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webSite', '0009_auto_20191227_0310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Semester',
            new_name='semester',
        ),
    ]
