# Generated by Django 2.2.5 on 2019-12-27 04:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webSite', '0011_student_research_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
    ]
