# Generated by Django 2.2.5 on 2019-12-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webSite', '0013_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(choices=[('st', 'by student'), ('pr', 'by professor'), ('ind', 'by industry')], max_length=256),
        ),
    ]
