# Generated by Django 2.2.5 on 2019-12-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webSite', '0014_auto_20191228_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='value',
            field=models.FloatField(),
        ),
    ]
