# Generated by Django 2.2.5 on 2019-12-28 06:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webSite', '0017_auto_20191228_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='given_by',
            field=models.ForeignKey(on_delete=models.SET('Deleted User'), related_name='grades_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='guid_instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('Deleted Professor'), related_name='students', to='webSite.Professor'),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('Deleted Semester'), related_name='students', to='webSite.Semester'),
        ),
    ]
