# Generated by Django 2.2.5 on 2019-12-31 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webSite', '0019_auto_20191228_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
            ],
        ),
    ]
