# Generated by Django 2.2.5 on 2019-12-31 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webSite', '0020_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(choices=[('by student', 'by student'), ('by professor', 'by professor'), ('by guide_professor', 'by guide_professor'), ('by industry', 'by industry')], max_length=256),
        ),
    ]
