# Generated by Django 2.2.5 on 2019-12-31 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webSite', '0022_auto_20191231_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
